version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'laravel'
        container_name: laravel-app
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
